feat: reworked `Connection` class
q-logic/python-spanner-django pull request #3
Opened 2020-09-02 13:19 UTC by paul1319

2020-09-02 21:33 UTC, mf2199 requested changes
OK for WIP but I'd give it another pass. Several methods can be removed or at least put in the design doc and discussed with Google before implementing. We should follow the published standards and the approved design - no more, no less. Also, the SQLs in L152-159 and L176-183 can be reformatted for consistency.

2020-09-02 21:33 UTC, mf2199 commented on spanner_dbapi/connection.py
> +from .exceptions import InterfaceError, Warning, ProgrammingError
Check whether these need to be put on different lines.

2020-09-02 21:33 UTC, mf2199 commented on spanner_dbapi/connection.py
> +
These blank lines are not necessary.

2020-09-02 21:33 UTC, mf2199 commented on spanner_dbapi/connection.py
> +        self.__ddl_statements = []
Is there a reason to use double-underscores here?

2020-09-02 21:33 UTC, mf2199 commented on spanner_dbapi/connection.py
> +def _is_conn_closed_check(func):
- First, I'd rename it to something like `_is_connection_closed` or `_connection_closed_check`.

- Secondly, this method can be put inside the `Connection` class.

- Lastly, I'm not even sure this method is even necessary: Spanner's `Transaction` class already [handles](https://github.com/googleapis/python-spanner/blob/ca82c1f0ae005e01ea31b0d7664e4415820429b9/google/cloud/spanner_v1/transaction.py#L53-L66) this check, while unnecessary usage of wrappers and decorators clutters the code.

2020-09-02 21:33 UTC, mf2199 commented on spanner_dbapi/connection.py
> +        return self.database.snapshot()
What is the specification that requires this method? If it's not listed in the design document or any other relevant specification sheet, or discussed and approved a priori by the Spanner team, then there is no reason to have it here at all.

2020-09-02 21:33 UTC, mf2199 commented on spanner_dbapi/connection.py
> +        self.__ddl_statements = []
Same with these.

2020-09-03 09:14 UTC, IlyaFaer commented on spanner_dbapi/connection.py
> +        return self.database.run_in_transaction(fn, *args, **kwargs)
I think we could rename this to `run_in_transaction` not to propagate different names to the same thing

2020-09-03 09:14 UTC, IlyaFaer commented on spanner_dbapi/connection.py
> +            raise Warning("'autocommit' is set to 'True'")
I'd say: `this connection is in autocommit mode - manual committing is off`

2020-09-03 09:14 UTC, IlyaFaer commented on spanner_dbapi/connection.py
> +        self.commit_timestamp = time.time()
`commit_timestamp` should be used only for `READ_WRITE` transactions

2020-09-03 09:14 UTC, IlyaFaer commented on spanner_dbapi/connection.py
> +)
Should be ordered

2020-09-03 09:14 UTC, IlyaFaer commented on spanner_dbapi/connection.py
> +    partitioned_non_atomic = "PARTITIONED_NON_ATOMIC"
Google usually use upper case for enum state names

2020-09-03 09:14 UTC, IlyaFaer commented on spanner_dbapi/connection.py
> +    def __init__(self, database, instance, autocommit=True, read_only=False):
On the last meeting with Chris it was decided not to add `autocommit` and `read_only` args for now. User can deal with them just by properties

2020-09-03 09:14 UTC, IlyaFaer commented on spanner_dbapi/connection.py
> +    def ddl_statements(self, dll):
`ddl`, not `dll`

2020-09-03 09:14 UTC, IlyaFaer commented on spanner_dbapi/connection.py
> +            self.commit()
Not sure if this is a good way of use: user changes the `ddl_statements` value, and it becomes commited in the same moment. It probably should be moved to `append_ddl_statements()`, while setting `ddl_statements` like "= value" should be disabled.

2020-09-03 09:14 UTC, IlyaFaer commented on spanner_dbapi/connection.py
> +        return self.database.snapshot()
This method better be renamed to `snapshot`

2020-09-03 13:30 UTC, IlyaFaer reviewed
Some property docstrings are missing, but mostly looks okay

2020-09-09 23:45 UTC, mf2199 requested changes
Unless I'm missing something, there's an apparent break of functionality after removing the "redundant" Connection methods, that needs to be addressed.

2020-09-09 23:45 UTC, mf2199 commented on spanner_dbapi/__init__.py
> +    return Connection(database, instance)
The `instance` reference can be accessed from within the [database](https://github.com/googleapis/python-spanner/blob/5fd4009dc8086e02b0deaa472f59958076c5a888/google/cloud/spanner_v1/database.py#L100).

2020-09-09 23:45 UTC, mf2199 commented on spanner_dbapi/connection.py
> +        self.instance = instance
Same here, can just use
```
    def __init__(self, database):
        self.database = database
```
and then referring to `instance` via `self.database._instance`.

2020-09-09 23:45 UTC, mf2199 commented on spanner_dbapi/cursor.py
> +        self._connection.run_in_transaction(
Where this `run_in_transaction` method is defined? Once you delete a dependency method from the `Connection` class, make sure its functionality is kept and/or transfered elsewhere, e.g., inside the `Cursor` class.

2020-09-09 23:45 UTC, mf2199 commented on spanner_dbapi/cursor.py
> +        with self._connection.snapshot() as snapshot:
I do not see the definition of the `snapshot` method in the `Connection` class either.

2020-09-09 23:45 UTC, mf2199 commented on spanner_dbapi/enums.py
> +    PARTITIONED_NON_ATOMIC = "PARTITIONED_NON_ATOMIC"
I really don't like using arbitrary strings in enums instead of integers, but that could be my personal preference.

2020-09-10 03:27 UTC, mf2199 reviewed
Couple more remarks.

2020-09-10 03:27 UTC, mf2199 commented on spanner_dbapi/connection.py
> +
According to [PEP-249](https://www.python.org/dev/peps/pep-0249/#cursor-objects), there may be more than one `Cursor` object linked to a single `Connection`. The references to those can be stored in a list-type of an attribute, e.g.,
```
        self.cursors = []
```
This list can be made "private", pending future decision. Better yet, it can also be a [WeakSet](https://docs.python.org/3/library/weakref.html#weakref.WeakSet), to assist in garbage collection.

2020-09-10 03:27 UTC, mf2199 commented on spanner_dbapi/connection.py
> +        return Cursor(self)
As mentioned in the previous comment, the reference can be added to the list prior to returning:
```
        cursor = Cursor(self)
        self.cursors.append(cursor)
        return cursor
```

2020-09-10 03:27 UTC, mf2199 commented on spanner_dbapi/connection.py
> +    @_connection_closed_check
Since this method does not do much and is present merely for standard compatibility, this decorator is redundant and can be removed.

2020-09-10 03:27 UTC, mf2199 commented on spanner_dbapi/connection.py
> +    @_connection_closed_check
Same here.

2020-09-10 03:27 UTC, mf2199 commented on spanner_dbapi/connection.py
> +    return wrapped
After all, it seems that the `@_connection_closed_check` can sensibly be used only once, see the comments below. Therefore we can safely remove this helper and replace the decorator with a simple two-liner check in the sole method that actually uses it.

2020-09-10 17:37 UTC, mf2199 reviewed
Couple more nits.

2020-09-10 17:37 UTC, mf2199 commented on spanner_dbapi/connection.py
> +from .enums import AutocommitDMLModes, TransactionModes
[PEP8](https://www.python.org/dev/peps/pep-0008/#id21) requires 2 blank lines between imports and global constants.

2020-09-10 17:37 UTC, mf2199 commented on spanner_dbapi/connection.py
> +            "Connection always works in `autocommit` mode, because of Spanner's limitations."
This can be rephrased, as "limitations" is not the most accurate word for it.

2020-09-10 17:37 UTC, mf2199 commented on spanner_dbapi/connection.py
> +            "Connection always works in `autocommit` mode, because of Spanner's limitations."
Same here.

2020-10-14 01:20 UTC, closed without merging